apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "windows-prometheus-sync.fullname" . }}
  labels:
    {{- include "windows-prometheus-sync.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "windows-prometheus-sync.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "windows-prometheus-sync.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "windows-prometheus-sync.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          # TODO: set these up
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          env:
            - name: METADATA_NAMESPACE
              value: {{ .Values.metadataNamespace }}
            - name: SCRAPE_CONFIG_SECRET_NAME
              value: {{ .Values.scrapeConfigSecretsName }}
            - name: SK__Kubernetes__NodeName
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: SK__Kubernetes__PodName
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SK__Kubernetes__PodNamespace
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SK__Kubernetes__PodIP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SK__Kubernetes__PodServiceAccount
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: SK__Kubernetes__ImageRepository
              value: {{ .Values.image.repository }}
            - name: SK__Kubernetes__ImageTag
              value: {{ .Values.image.tag | default .Chart.AppVersion }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
