{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "windows-prometheus-sync.serviceAccountName" . }}
  labels:
    {{- include "windows-prometheus-sync.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "windows-prometheus-sync.serviceAccountName" . }}-reader
  labels:
    {{- include "windows-prometheus-sync.labels" . | nindent 4 }}
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: 
      - nodes
    verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "windows-prometheus-sync.serviceAccountName" . }}-reader-binding
  labels:
    {{- include "windows-prometheus-sync.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "windows-prometheus-sync.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "windows-prometheus-sync.serviceAccountName" . }}-reader
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "windows-prometheus-sync.serviceAccountName" . }}-secret-modifier
  namespace: monitoring
  labels:
    {{- include "windows-prometheus-sync.labels" . | nindent 4 }}
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["secrets"]
    resourceNames: ["kube-prometheus-stack-prometheus-scrape-confg"]
    verbs: ["get", "watch", "list", "update", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "windows-prometheus-sync.serviceAccountName" . }}-secret-modifier-binding
  labels:
    {{- include "windows-prometheus-sync.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "windows-prometheus-sync.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "windows-prometheus-sync.serviceAccountName" . }}-secret-modifier
  apiGroup: rbac.authorization.k8s.io
{{- end }}
